apiVersion: v2
name: backend
description: A Helm chart for deploying Backend component in Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.7.1
    condition: db.enabled
    alias: db
